apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/GoogleCloudPlatform/k8s-config-connector/v1.86.0/install-bundles/install-bundle-workload-identity/crds.yaml
- https://raw.githubusercontent.com/GoogleCloudPlatform/k8s-config-connector/v1.86.0/install-bundles/install-bundle-workload-identity/0-cnrm-system.yaml
